[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    refreshPeriod = "168h"
#[".config/hyde/themes"]
#  type = "git-repo"
#  url = "https://github.com/foglar/wallpapers.git"
#  refreshPeriod = "168h"
