[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    refreshPeriod = "168h"
[".config/dotfiles/grub-theme/"]
  type = "archive"
  url = "https://github.com/xenlism/Grub-themes/raw/main/xenlism-grub-arch-1080p.tar.xz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".config/dotfiles/themes"]
  type = "git-repo"
  url = "https://github.com/foglar/wallpapers.git"
  refreshPeriod = "168h"
