packages:
  linux:
    terminal:
      - 1password
      - ark
      - auto-cpufreq
      - clamtk
      - cups
      - hplip
      - dolphin
      - kdeconnect
      - loupe
      - vlc
      - stellarium
      - gnome-disk-utility
      - gimp
      - inkscape
      - openrocket
      - spectacle
      - spicetify-cli
      - spicetify-themes-git
      - spotify-launcher
      - spotube
      - virt-manager
      - virt-viewer
      - whatsie
      - libreoffice-fresh
      - easytag
      - kalk
      - localsend-bin
      - audacity
      - firefox
      - discord
      - librewolf-bin
      - qbittorrent
      - tor-browser
      - heroic-games-launcher-bin
      - steam
      - gamemode
      - gamescope
      - mangohud
      - yetris
      - wine
      - arduino-avr-core
      - arduino-cli
      - arduino-ide-bin
      - docker
      - dotnet-sdk
      - git
      - git-credential-manager-core-bin
      - github-cli
      - gitkraken
      - go
      - jdk-openjdk
      - jdk17-openjdk
      - jq
      - kitty
      - konsole
      - mingw-w64-gcc
      - neovim
      - npm
      - termius
      - visual-studio-code-bin
      - 1password-cli
      - bash-completion
      - bat
      - bluez
      - bluez-utils
      - btop
      - chezmoi
      - cmatrix
      - entr
      - espeak-ng
      - evince
      - eza
      - figlet
      - fzf
      - htop
      - jp2a
      - lolcat
      - man-db
      - mdp
      - ncdu
      - neofetch
      - neovim
      - nvtop
      - oh-my-posh
      - oh-my-zsh-git
      - openssh
      - parallel
      - paru
      - paru-debug
      - pfetch
      - ranger
      - ripgrep
      - slurp
      - snapper
      - tldr
      - tmux
      - unzip
      - w3m
      - wget
      - yt-dlp
      - zoxide
      - zsh
      - noto-fonts-emoji
      - ttf-jetbrains-mono-nerd
